# Generated by Django 4.1 on 2022-08-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodcutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('SKU', models.CharField(max_length=50, unique=True)),
                ('tag_product', models.CharField(max_length=50)),
                ('cost', models.IntegerField(max_length=10)),
                ('status', models.CharField(choices=[('active', 'active'), ('archived', 'archived'), ('draft', 'draft')], max_length=10)),
                ('tallas', models.CharField(max_length=50)),
                ('crate', models.DateTimeField(auto_now_add=True)),
                ('up_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
