# Generated by Django 4.1 on 2022-08-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcutos',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
