# Generated by Django 4.1 on 2022-08-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_prodcutos_crate_alter_prodcutos_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcutos',
            name='crate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prodcutos',
            name='up_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
